name: tests

on: [ push ]

jobs:
  tests:
    name: Test SCHISM build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install netCDF4 library on Linux
        run: sudo apt-get update -y && sudo apt-get install -y libnetcdf-dev libnetcdff-dev cmake openmpi-bin libopenmpi-dev g++ python
      - name: Compile SCHISM
        shell: bash
        env:
        CC:   gcc-4
        CXX:  g++-4
        FC: gfortran-4
        run: |
          mkdir build
          cd build
          cmake ../src \
          -DNetCDF_Fortran_LIBRARY=$(nf-config --prefix)/lib/libnetcdff.so \
          -DNetCDF_INCLUDE_DIRS=$(nc-config --includedir) \
          -DNetCDF_C_LIBRARY=$(nc-config --prefix)/lib/libnetcdf.so
          make -j$(nproc)
